# Generated by Django 5.1.6 on 2025-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0004_alter_trial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='status',
            field=models.TextField(default='do akceptacji przez opiekuna'),
        ),
    ]
