module.exports = {
    darkMode: 'class',
    content: [
      './index.html',
      './src/**/*.{js,jsx,ts,tsx}',
    ],
    safelist: [
      // Kolory tła kategorii
      'bg-purple-200',
      'bg-amber-200',
      'bg-blue-200',
      'bg-yellow-200',
      'bg-gray-700',
      'bg-pink-200',
      'bg-green-200',
      'bg-fuchsia-200',
      'bg-lime-200',
      'bg-cyan-200',
      'bg-rose-300',
      'bg-slate-200',
      // Kolory tekstu kategorii
      'text-purple-900',
      'text-amber-700',
      'text-blue-900',
      'text-yellow-700',
      'text-gray-200',
      'text-pink-900',
      'text-green-900',
      'text-fuchsia-900',
      'text-lime-900',
      'text-cyan-700',
      'text-rose-800',
      'text-slate-900',
      // Dark mode - tła
      'dark:bg-purple-800',
      'dark:bg-amber-700',
      'dark:bg-blue-800',
      'dark:bg-yellow-600',
      'dark:bg-black',
      'dark:bg-pink-800',
      'dark:bg-green-800',
      'dark:bg-fuchsia-800',
      'dark:bg-lime-800',
      'dark:bg-cyan-600',
      'dark:bg-rose-700',
      'dark:bg-slate-200',
      // Dark mode - teksty
      'dark:text-purple-200',
      'dark:text-amber-100',
      'dark:text-blue-200',
      'dark:text-yellow-100',
      'dark:text-gray-200',
      'dark:text-pink-200',
      'dark:text-green-200',
      'dark:text-fuchsia-200',
      'dark:text-lime-200',
      'dark:text-cyan-100',
      'dark:text-rose-200',
      'dark:text-slate-900',
    ],
    theme: {
      extend: {},
    },
    plugins: [],
  };