# Generated by Django 5.1.6 on 2025-02-22 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='trials.trial'),
        ),
    ]
