# Generated by Django 5.1.6 on 2025-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
